#!/usr/bin/env python3
"""One capability, one set of facts, on every surface that renders it.

WHY THIS IS THE TEST THAT MATTERS MOST. The product's whole claim is that a number is re-derivable
from public evidence. A reader who sees tashan score 96 on the board, 96 in the CLI and 93 on the
category hub does not conclude "one of these pages is stale" — they conclude the measurement is
made up, and they are right to. Disagreement between our own surfaces is not a rendering bug, it is
a claim we cannot support, and it costs more trust than a missing feature ever would.

A capability is rendered on up to eight surfaces, each generated by different code:

  web/data/capabilities.json   the export — SOURCE OF TRUTH, everything else is derived from it
  web/data/index.json          the board (slim, build.py SLIM)
  web/data/lookup.json         the CLI and the MCP server (build.py LOOKUP)
  web/capability/<slug>.html   the prerendered dossier (prerender.py)
  web/category/<cat>.html      the category hub table (gen_hubs.py)
  web/task/<t>.html            the task hub table (gen_hubs.py)
  web/llms.txt                 the answer-engine feed (gen_hubs.py)
  web/badge/<slug>.svg         the embeddable badge (gen_badges.py)

Four generators, three renderers, one set of facts. They have drifted before — this codebase has
already shipped a hub table whose row anatomy disagreed with the board, a sort reading a column
that had been renamed away, and a nav in six variants. The fix each time was one definition; this
is what proves the definitions stayed one.

FIRST RUN CAUGHT: llms.txt published "[filesystem]" where every other surface said "Filesystem",
because gen_hubs.py had three display sites still calling pretty() after the label landed.

Run: python3 tests/test_consistency.py
"""
import collections, glob, html, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")

fail = 0
SAMPLE = int(os.environ.get("CONSISTENCY_SAMPLE", "0"))     # 0 = every capability


def ok(name, cond, detail=""):
    global fail
    if not cond:
        fail = 1
    print(("  ok   " if cond else "  FAIL ") + name + (("  — " + detail) if detail and not cond else ""))


def load(rel):
    p = os.path.join(WEB, rel)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def caps_of(d):
    return d["capabilities"] if isinstance(d, dict) else d


unesc = lambda s: html.unescape(s or "").strip()

# ---- the source of truth -------------------------------------------------------------------------
export = load("data/capabilities.json")
if not export:
    print("  FAIL  web/data/capabilities.json missing — run the export")
    sys.exit(1)
TRUTH = {c["id"]: c for c in caps_of(export)}
print(f"  source of truth: {len(TRUTH)} capabilities in capabilities.json\n")

# ---- 1. the derived JSON payloads ----------------------------------------------------------------
# These are cheap to check exhaustively and are what every client actually reads.
for rel, fields in (("data/index.json", ("label", "tashan_score", "category", "official", "kind",
                                         "expertise_verdict", "npm_pkg")),
                    ("data/lookup.json", ("label", "tashan_score", "category", "official"))):
    d = load(rel)
    if d is None:
        ok(f"{rel} exists", False)
        continue
    rows = d.get("records") if isinstance(d, dict) and "records" in d else caps_of(d)
    rowsById = {r["id"]: r for r in rows}
    missing = [r["id"] for r in rows if r["id"] not in TRUTH]
    if rel.endswith("lookup.json"):
        # lookup.json is ALLOWED to carry rows the board does not, and must: junk() drops
        # registry-deleted entries and the two dependency-confusion canaries off the board, and they
        # survive here so `tashan doctor` can warn somebody already running one. Silence would be the
        # bug. But each survivor needs a REASON — an orphan with no warning attached is just drift.
        unexplained = [i for i in missing
                       if not (rowsById[i].get("registry_status") == "deleted"
                               or rowsById[i].get("sec_advisory_count")
                               or rowsById[i].get("sec_severity"))]
        ok(f"{rel}: all {len(missing)} board-excluded row(s) are kept deliberately, to warn about",
           not unexplained, f"{len(unexplained)} unexplained orphan(s): {unexplained[:3]}")
    else:
        ok(f"{rel}: every row exists in the export", not missing,
           f"{len(missing)} orphan(s), e.g. {missing[:3]}")
    bad = collections.Counter()
    examples = {}
    for r in rows:
        t = TRUTH.get(r["id"])
        if not t:
            continue
        for f in fields:
            if f in r and r[f] != t.get(f):
                bad[f] += 1
                examples.setdefault(f, f"{r['id']}: {rel}={r[f]!r} export={t.get(f)!r}")
    ok(f"{rel}: {len(rows)} rows agree with the export on {len(fields)} fields",
       not bad, "; ".join(f"{f} differs on {n} row(s) — {examples[f]}" for f, n in bad.most_common(3)))

# ---- 2. the prerendered dossiers -----------------------------------------------------------------
H1 = re.compile(r"<h1>(.*?)</h1>", re.S)
CATLINK = re.compile(r'<b>Category:</b>\s*<a class="link" href="/category/([a-z]+)\.html">')
OFFICIAL = re.compile(r'<span class="official">✓\s*(.*?)\s*·\s*official</span>')
DESC = re.compile(r'<p class="cap-desc">(.*?)</p>', re.S)
SCORE = re.compile(r"tashan score[^0-9]{0,40}([0-9]+(?:\.[0-9]+)?)", re.I)

pages = sorted(glob.glob(os.path.join(WEB, "capability", "*.html")))
if SAMPLE:
    pages = pages[::max(1, len(pages) // SAMPLE)]
slug_to_id = {c.get("slug") or re.sub(r"[^a-z0-9]+", "-", c["id"].lower()).strip("-"): c["id"]
              for c in TRUTH.values()}

mismatch = collections.Counter()
examples = {}
checked = 0
orphan_pages = []
for p in pages:
    slug = os.path.basename(p)[:-5]
    cid = slug_to_id.get(slug)
    if not cid:
        orphan_pages.append(slug)
        continue
    t = TRUTH[cid]
    src = open(p, encoding="utf-8").read()
    checked += 1

    m = H1.search(src)
    want_label = t.get("label") or t.get("name")
    if m:
        got = unesc(re.sub(r"<[^>]+>", "", m.group(1)))
        if got != unesc(want_label):
            mismatch["label"] += 1
            examples.setdefault("label", f"{slug}: page={got!r} export={want_label!r}")

    m = CATLINK.search(src)
    if m and t.get("category") and m.group(1) != t["category"]:
        mismatch["category"] += 1
        examples.setdefault("category", f"{slug}: page={m.group(1)} export={t['category']}")

    m = OFFICIAL.search(src)
    page_official = unesc(m.group(1)) if m else None
    if page_official != (t.get("official") or None):
        mismatch["official"] += 1
        examples.setdefault("official", f"{slug}: page={page_official!r} export={t.get('official')!r}")

    m = DESC.search(src)
    if m and t.get("description"):
        got = unesc(re.sub(r"<[^>]+>", "", m.group(1)))
        if got != unesc(t["description"])[:len(got)]:
            mismatch["description"] += 1
            examples.setdefault("description", f"{slug}: page={got[:50]!r}")

ok(f"every /capability/*.html page corresponds to an exported capability", not orphan_pages,
   f"{len(orphan_pages)} orphan page(s), e.g. {orphan_pages[:3]}")
ok(f"{checked} prerendered dossiers agree with the export (label, category, official, description)",
   not mismatch,
   "; ".join(f"{k} on {n} page(s) — {examples[k]}" for k, n in mismatch.most_common(4)))

# ---- 3. the hub tables ---------------------------------------------------------------------------
# A hub row that names a capability differently from its own dossier is the exact defect that shipped
# once already: a hub table with a different row anatomy from the board.
# Anchor on the LINK, not on any href: the row's <tr data-href=…> carries the same URL, and matching
# that first swallowed the rank cell, so every row read as "1Sequential Thinking".
ROW = re.compile(r'<a class="cap__link" href="/capability/([a-z0-9-]+)\.html">(.*?)</a>', re.S)
hub_bad = collections.Counter()
hub_ex = {}
hub_rows = 0
for hub in sorted(glob.glob(os.path.join(WEB, "category", "*.html")) +
                  glob.glob(os.path.join(WEB, "task", "*.html"))):
    src = open(hub, encoding="utf-8").read()
    cat = os.path.basename(hub)[:-5]
    is_cat = os.path.dirname(hub).endswith("category")
    for slug, inner in ROW.findall(src):
        cid = slug_to_id.get(slug)
        if not cid:
            hub_bad["dead link"] += 1
            hub_ex.setdefault("dead link", f"{os.path.basename(hub)} -> /capability/{slug}.html")
            continue
        t = TRUTH[cid]
        hub_rows += 1
        got = unesc(re.sub(r"<[^>]+>", "", inner))
        want = unesc(t.get("label") or t.get("name"))
        if got and got != want:
            hub_bad["label"] += 1
            hub_ex.setdefault("label", f"{os.path.basename(hub)}: {got!r} vs export {want!r}")
        # a capability must only appear on the hub for the category it is actually in
        if is_cat and t.get("category") and t["category"] != cat:
            hub_bad["wrong hub"] += 1
            hub_ex.setdefault("wrong hub", f"{slug} is '{t['category']}' but listed on /category/{cat}.html")

ok(f"{hub_rows} category/task hub rows name the capability exactly as its dossier does",
   not hub_bad, "; ".join(f"{k} x{n} — {hub_ex[k]}" for k, n in hub_bad.most_common(3)))

# ---- 4. llms.txt — what answer engines quote ------------------------------------------------------
llms = os.path.join(WEB, "llms.txt")
if os.path.exists(llms):
    src = open(llms, encoding="utf-8").read()
    bad, ex = collections.Counter(), {}
    n = 0
    for label, slug, score in re.findall(
            r"- \[([^\]]+)\]\([^)]*?/capability/([a-z0-9-]+)\.html\)\s*—\s*tashan score ([0-9.]+)", src):
        cid = slug_to_id.get(slug)
        if not cid:
            bad["dead link"] += 1
            ex.setdefault("dead link", slug)
            continue
        t = TRUTH[cid]
        n += 1
        if unesc(label) != unesc(t.get("label") or t.get("name")):
            bad["label"] += 1
            ex.setdefault("label", f"llms.txt={label!r} export={(t.get('label') or t.get('name'))!r}")
        if t.get("tashan_score") is not None and float(score) != float(t["tashan_score"]):
            bad["score"] += 1
            ex.setdefault("score", f"{slug}: llms.txt={score} export={t['tashan_score']}")
    ok(f"llms.txt: {n} cited capabilities match the export on name and score",
       not bad, "; ".join(f"{k} x{v} — {ex[k]}" for k, v in bad.most_common(3)))

# ---- 5. badges -----------------------------------------------------------------------------------
# 8,394 badge files against 5,788 pages was the smell that started this check.
badges = glob.glob(os.path.join(WEB, "badge", "*.svg"))
stale = [os.path.basename(b)[:-4] for b in badges if os.path.basename(b)[:-4] not in slug_to_id]
ok(f"every one of the {len(badges)} badges belongs to a capability still in the export",
   not stale, f"{len(stale)} badge(s) for capabilities no longer exported, e.g. {stale[:3]}")

print("\nCONSISTENCY FAILED" if fail else "\nok — one capability, one set of facts, every surface")
sys.exit(fail)
