#!/usr/bin/env python3
"""One capability, one set of facts, on every surface that renders it.

WHY THIS IS THE TEST THAT MATTERS MOST. The product's whole claim is that a number is re-derivable
from public evidence. A reader who sees tashan score 96 on the board, 96 in the CLI and 93 on the
category hub does not conclude "one of these pages is stale" — they conclude the measurement is
made up, and they are right to. Disagreement between our own surfaces is not a rendering bug, it is
a claim we cannot support, and it costs more trust than a missing feature ever would.

A capability is rendered on up to eight surfaces, each generated by different code:

  web/data/capabilities.json   the export — SOURCE OF TRUTH, everything else is derived from it
  web/data/index.json          the board (slim, build.py SLIM)
  web/data/lookup.json         the CLI and the MCP server (build.py LOOKUP)
  web/capability/<slug>.html   the prerendered dossier (prerender.py)
  web/category/<cat>.html      the category hub table (gen_hubs.py)
  web/task/<t>.html            the task hub table (gen_hubs.py)
  web/llms.txt                 the answer-engine feed (gen_hubs.py)
  web/badge/<slug>.svg         the embeddable badge (gen_badges.py)

Four generators, three renderers, one set of facts. They have drifted before — this codebase has
already shipped a hub table whose row anatomy disagreed with the board, a sort reading a column
that had been renamed away, and a nav in six variants. The fix each time was one definition; this
is what proves the definitions stayed one.

FIRST RUN CAUGHT: llms.txt published "[filesystem]" where every other surface said "Filesystem",
because gen_hubs.py had three display sites still calling pretty() after the label landed.

Run: python3 tests/test_consistency.py
"""
import collections, glob, html, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")

fail = 0
SAMPLE = int(os.environ.get("CONSISTENCY_SAMPLE", "0"))     # 0 = every capability


def ok(name, cond, detail=""):
    global fail
    if not cond:
        fail = 1
    print(("  ok   " if cond else "  FAIL ") + name + (("  — " + detail) if detail and not cond else ""))


def load(rel):
    p = os.path.join(WEB, rel)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def caps_of(d):
    return d["capabilities"] if isinstance(d, dict) else d


unesc = lambda s: html.unescape(s or "").strip()

# ---- the source of truth -------------------------------------------------------------------------
export = load("data/capabilities.json")
if not export:
    print("  FAIL  web/data/capabilities.json missing — run the export")
    sys.exit(1)
TRUTH = {c["id"]: c for c in caps_of(export)}
print(f"  source of truth: {len(TRUTH)} capabilities in capabilities.json\n")

# ---- 1. the derived JSON payloads ----------------------------------------------------------------
# These are cheap to check exhaustively and are what every client actually reads.
for rel, fields in (("data/index.json", ("label", "tashan_score", "category", "official", "kind",
                                         "expertise_verdict", "npm_pkg")),
                    ("data/lookup.json", ("label", "tashan_score", "category", "official"))):
    d = load(rel)
    if d is None:
        ok(f"{rel} exists", False)
        continue
    rows = d.get("records") if isinstance(d, dict) and "records" in d else caps_of(d)
    rowsById = {r["id"]: r for r in rows}
    missing = [r["id"] for r in rows if r["id"] not in TRUTH]
    if rel.endswith("lookup.json"):
        # lookup.json is ALLOWED to carry rows the board does not, and must: junk() drops
        # registry-deleted entries and the two dependency-confusion canaries off the board, and they
        # survive here so `tashan doctor` can warn somebody already running one. Silence would be the
        # bug. But each survivor needs a REASON — an orphan with no warning attached is just drift.
        unexplained = [i for i in missing
                       if not (rowsById[i].get("registry_status") == "deleted"
                               or rowsById[i].get("sec_advisory_count")
                               or rowsById[i].get("sec_severity"))]
        ok(f"{rel}: all {len(missing)} board-excluded row(s) are kept deliberately, to warn about",
           not unexplained, f"{len(unexplained)} unexplained orphan(s): {unexplained[:3]}")
    else:
        ok(f"{rel}: every row exists in the export", not missing,
           f"{len(missing)} orphan(s), e.g. {missing[:3]}")
    bad = collections.Counter()
    examples = {}
    for r in rows:
        t = TRUTH.get(r["id"])
        if not t:
            continue
        for f in fields:
            if f in r and r[f] != t.get(f):
                bad[f] += 1
                examples.setdefault(f, f"{r['id']}: {rel}={r[f]!r} export={t.get(f)!r}")
    ok(f"{rel}: {len(rows)} rows agree with the export on {len(fields)} fields",
       not bad, "; ".join(f"{f} differs on {n} row(s) — {examples[f]}" for f, n in bad.most_common(3)))

# ---- 2. the prerendered dossiers -----------------------------------------------------------------
H1 = re.compile(r"<h1>(.*?)</h1>", re.S)
CATLINK = re.compile(r'<b>Category:</b>\s*<a class="link" href="/category/([a-z]+)\.html">')
OFFICIAL = re.compile(r'<span class="official">✓\s*(.*?)\s*·\s*official</span>')
DESC = re.compile(r'<p class="cap-desc">(.*?)</p>', re.S)
SCORE = re.compile(r"tashan score[^0-9]{0,40}([0-9]+(?:\.[0-9]+)?)", re.I)

pages = sorted(glob.glob(os.path.join(WEB, "capability", "*.html")))
if SAMPLE:
    pages = pages[::max(1, len(pages) // SAMPLE)]
slug_to_id = {c.get("slug") or re.sub(r"[^a-z0-9]+", "-", c["id"].lower()).strip("-"): c["id"]
              for c in TRUTH.values()}

mismatch = collections.Counter()
examples = {}
checked = 0
orphan_pages = []
for p in pages:
    slug = os.path.basename(p)[:-5]
    cid = slug_to_id.get(slug)
    if not cid:
        orphan_pages.append(slug)
        continue
    t = TRUTH[cid]
    src = open(p, encoding="utf-8").read()
    checked += 1

    m = H1.search(src)
    want_label = t.get("label") or t.get("name")
    if m:
        got = unesc(re.sub(r"<[^>]+>", "", m.group(1)))
        if got != unesc(want_label):
            mismatch["label"] += 1
            examples.setdefault("label", f"{slug}: page={got!r} export={want_label!r}")

    m = CATLINK.search(src)
    if m and t.get("category") and m.group(1) != t["category"]:
        mismatch["category"] += 1
        examples.setdefault("category", f"{slug}: page={m.group(1)} export={t['category']}")

    m = OFFICIAL.search(src)
    page_official = unesc(m.group(1)) if m else None
    if page_official != (t.get("official") or None):
        mismatch["official"] += 1
        examples.setdefault("official", f"{slug}: page={page_official!r} export={t.get('official')!r}")

    m = DESC.search(src)
    if m and t.get("description"):
        got = unesc(re.sub(r"<[^>]+>", "", m.group(1)))
        if got != unesc(t["description"])[:len(got)]:
            mismatch["description"] += 1
            examples.setdefault("description", f"{slug}: page={got[:50]!r}")

ok(f"every /capability/*.html page corresponds to an exported capability", not orphan_pages,
   f"{len(orphan_pages)} orphan page(s), e.g. {orphan_pages[:3]}")
ok(f"{checked} prerendered dossiers agree with the export (label, category, official, description)",
   not mismatch,
   "; ".join(f"{k} on {n} page(s) — {examples[k]}" for k, n in mismatch.most_common(4)))

# ---- 3. the hub tables ---------------------------------------------------------------------------
# A hub row that names a capability differently from its own dossier is the exact defect that shipped
# once already: a hub table with a different row anatomy from the board.
# Anchor on the LINK, not on any href: the row's <tr data-href=…> carries the same URL, and matching
# that first swallowed the rank cell, so every row read as "1Sequential Thinking".
ROW = re.compile(r'<a class="cap__link" href="/capability/([a-z0-9-]+)\.html">(.*?)</a>', re.S)
hub_bad = collections.Counter()
hub_ex = {}
hub_rows = 0
for hub in sorted(glob.glob(os.path.join(WEB, "category", "*.html")) +
                  glob.glob(os.path.join(WEB, "task", "*.html"))):
    src = open(hub, encoding="utf-8").read()
    cat = os.path.basename(hub)[:-5]
    is_cat = os.path.dirname(hub).endswith("category")
    for slug, inner in ROW.findall(src):
        cid = slug_to_id.get(slug)
        if not cid:
            hub_bad["dead link"] += 1
            hub_ex.setdefault("dead link", f"{os.path.basename(hub)} -> /capability/{slug}.html")
            continue
        t = TRUTH[cid]
        hub_rows += 1
        got = unesc(re.sub(r"<[^>]+>", "", inner))
        want = unesc(t.get("label") or t.get("name"))
        if got and got != want:
            hub_bad["label"] += 1
            hub_ex.setdefault("label", f"{os.path.basename(hub)}: {got!r} vs export {want!r}")
        # a capability must only appear on the hub for the category it is actually in
        if is_cat and t.get("category") and t["category"] != cat:
            hub_bad["wrong hub"] += 1
            hub_ex.setdefault("wrong hub", f"{slug} is '{t['category']}' but listed on /category/{cat}.html")

ok(f"{hub_rows} category/task hub rows name the capability exactly as its dossier does",
   not hub_bad, "; ".join(f"{k} x{n} — {hub_ex[k]}" for k, n in hub_bad.most_common(3)))

# ---- 4. llms.txt — what answer engines quote ------------------------------------------------------
llms = os.path.join(WEB, "llms.txt")
if os.path.exists(llms):
    src = open(llms, encoding="utf-8").read()
    bad, ex = collections.Counter(), {}
    n = 0
    for label, slug, score in re.findall(
            r"- \[([^\]]+)\]\([^)]*?/capability/([a-z0-9-]+)\.html\)\s*—\s*tashan score ([0-9.]+)", src):
        cid = slug_to_id.get(slug)
        if not cid:
            bad["dead link"] += 1
            ex.setdefault("dead link", slug)
            continue
        t = TRUTH[cid]
        n += 1
        if unesc(label) != unesc(t.get("label") or t.get("name")):
            bad["label"] += 1
            ex.setdefault("label", f"llms.txt={label!r} export={(t.get('label') or t.get('name'))!r}")
        if t.get("tashan_score") is not None and float(score) != float(t["tashan_score"]):
            bad["score"] += 1
            ex.setdefault("score", f"{slug}: llms.txt={score} export={t['tashan_score']}")
    ok(f"llms.txt: {n} cited capabilities match the export on name and score",
       not bad, "; ".join(f"{k} x{v} — {ex[k]}" for k, v in bad.most_common(3)))

# ---- 5. badges -----------------------------------------------------------------------------------
# 8,394 badge files against 5,788 pages was the smell that started this check.
badges = glob.glob(os.path.join(WEB, "badge", "*.svg"))
stale = [os.path.basename(b)[:-4] for b in badges if os.path.basename(b)[:-4] not in slug_to_id]
ok(f"every one of the {len(badges)} badges belongs to a capability still in the export",
   not stale, f"{len(stale)} badge(s) for capabilities no longer exported, e.g. {stale[:3]}")

# ---- 6. THE NUMBER ITSELF --------------------------------------------------------------------
# Identity being consistent is table stakes; the SCORE is the claim people act on, and it is printed
# on six surfaces by four different code paths. The first version of this file checked it only in the
# JSON payloads and llms.txt — not in the 5,788 rendered dossiers, not in the hub tables, not in the
# badge someone embeds in their README, and not in the JSON-LD an answer engine parses. Those are
# precisely the copies a reader quotes back at you.
DOSSIER_SCORE = re.compile(r"tashan score ([0-9]+(?:\.[0-9]+)?)")
LD_RATING = re.compile(r'"ratingValue":\s*([0-9.]+)')
TITLE = re.compile(r"<title>(.*?)</title>", re.S)

num_bad = collections.Counter()
num_ex = {}
n_scored = 0
for p_ in pages:
    slug = os.path.basename(p_)[:-5]
    cid = slug_to_id.get(slug)
    if not cid:
        continue
    t = TRUTH[cid]
    want = t.get("tashan_score")
    if want is None:
        continue
    src = open(p_, encoding="utf-8").read()
    n_scored += 1

    for rx, key in ((DOSSIER_SCORE, "dossier score"), (LD_RATING, "JSON-LD ratingValue")):
        for got in rx.findall(src):
            if abs(float(got) - float(want)) > 0.05:
                num_bad[key] += 1
                num_ex.setdefault(key, f"{slug}: page={got} export={want}")
                break

    m = TITLE.search(src)
    if m and unesc(t.get("label") or t.get("name")) not in unesc(m.group(1)):
        num_bad["<title> names the capability"] += 1
        num_ex.setdefault("<title> names the capability",
                          f"{slug}: title={unesc(m.group(1))[:44]!r} label={t.get('label')!r}")

ok(f"{n_scored} dossiers print the same tashan score as the export, in body text AND JSON-LD",
   not num_bad, "; ".join(f"{k} wrong on {v} page(s) — {num_ex[k]}" for k, v in num_bad.most_common(3)))

# hub tables print the score in a <span class="sig__val">, rounded
HUBROW = re.compile(
    r'<tr data-href="/capability/([a-z0-9-]+)\.html">.*?<span class="sig__val">([0-9]+)</span>', re.S)
hub_score_bad = collections.Counter()
hsx = {}
n_hub = 0
for hub in sorted(glob.glob(os.path.join(WEB, "category", "*.html")) +
                  glob.glob(os.path.join(WEB, "task", "*.html"))):
    for slug, got in HUBROW.findall(open(hub, encoding="utf-8").read()):
        cid = slug_to_id.get(slug)
        if not cid or TRUTH[cid].get("tashan_score") is None:
            continue
        n_hub += 1
        want = round(float(TRUTH[cid]["tashan_score"]))
        if int(got) != want:
            hub_score_bad[os.path.basename(hub)] += 1
            hsx.setdefault("x", f"{slug} on {os.path.basename(hub)}: hub={got} export={want}")
ok(f"{n_hub} hub rows print the same score as the export",
   not hub_score_bad, hsx.get("x", ""))

# the badge is the copy that ends up in somebody else's README, where we cannot correct it
BADGE = re.compile(r'aria-label="tashan:\s*([0-9]+)')
badge_bad = collections.Counter()
bx = {}
n_badge = 0
for b in sorted(glob.glob(os.path.join(WEB, "badge", "*.svg"))):
    slug = os.path.basename(b)[:-4]
    cid = slug_to_id.get(slug)
    if not cid or TRUTH[cid].get("tashan_score") is None:
        continue
    m = BADGE.search(open(b, encoding="utf-8").read())
    if not m:
        continue
    n_badge += 1
    want = round(float(TRUTH[cid]["tashan_score"]))
    if int(m.group(1)) != want:
        badge_bad["score"] += 1
        bx.setdefault("score", f"{slug}: badge={m.group(1)} export={want}")
ok(f"{n_badge} badges carry the same score as the export",
   not badge_bad, bx.get("score", ""))

# ---- 7. the security audit, on the canonical page ------------------------------------------------
# It lived only in capability.js, which rewrites the dossier client-side — so a person saw the audit
# and a crawler did not, on the one measurement nobody else publishes. Now prerendered. The
# trust-critical assertion is the negative one: a capability we did NOT scan must never render a
# sentence that could be read as "we scanned it and it was clean".
sec_bad = collections.Counter()
sec_ex = {}
n_scanned = n_unscanned = 0
for p_ in pages:
    cid = slug_to_id.get(os.path.basename(p_)[:-5])
    if not cid:
        continue
    t = TRUTH[cid]
    src = open(p_, encoding="utf-8").read()
    slug = os.path.basename(p_)[:-5]

    if "Security audit" not in src:
        sec_bad["no security section at all"] += 1
        sec_ex.setdefault("no security section at all", slug)
        continue

    if not t.get("sec_scanned_at"):
        n_unscanned += 1
        if "Not scanned yet" not in src:
            sec_bad["unscanned page does not say so"] += 1
            sec_ex.setdefault("unscanned page does not say so", slug)
        for claim in ("No known advisories", "checked against OSV", "No permission surface detected"):
            if claim in src:
                sec_bad["unscanned page implies a clean scan"] += 1
                sec_ex.setdefault("unscanned page implies a clean scan", f"{slug}: {claim!r}")
                break
        continue

    n_scanned += 1
    n_adv = t.get("sec_advisory_count") or 0
    if n_adv and f"{n_adv} known advisor" not in src:
        sec_bad["advisory count"] += 1
        sec_ex.setdefault("advisory count", f"{slug}: export says {n_adv}")
    if not n_adv and "No known advisories" not in src:
        sec_bad["clear result not stated"] += 1
        sec_ex.setdefault("clear result not stated", slug)
    if bool(t.get("sec_install_script")) != ("Runs a script at install time" in src):
        sec_bad["install script"] += 1
        sec_ex.setdefault("install script", f"{slug}: export={bool(t.get('sec_install_script'))}")
    if bool(t.get("sec_provenance")) != ("Signed build provenance" in src):
        sec_bad["provenance"] += 1
        sec_ex.setdefault("provenance", f"{slug}: export={bool(t.get('sec_provenance'))}")

ok(f"{n_scanned} scanned + {n_unscanned} unscanned dossiers state their security result truthfully",
   not sec_bad, "; ".join(f"{k} x{v} — {sec_ex[k]}" for k, v in sec_bad.most_common(3)))

print("\nCONSISTENCY FAILED" if fail else "\nok — one capability, one set of facts, every surface")
sys.exit(fail)
