#!/usr/bin/env python3
"""One capability, one set of facts, on every surface that renders it.

WHY THIS IS THE TEST THAT MATTERS MOST. The product's whole claim is that a number is re-derivable
from public evidence. A reader who sees tashan score 96 on the board, 96 in the CLI and 93 on the
category hub does not conclude "one of these pages is stale" — they conclude the measurement is
made up, and they are right to. Disagreement between our own surfaces is not a rendering bug, it is
a claim we cannot support, and it costs more trust than a missing feature ever would.

A capability is rendered on up to eight surfaces, each generated by different code:

  web/data/capabilities.json   the export — SOURCE OF TRUTH, everything else is derived from it
  web/data/index.json          the board (slim, build.py SLIM)
  web/data/lookup.json         the CLI and the MCP server (build.py LOOKUP)
  web/capability/<slug>.html   the prerendered dossier (prerender.py)
  web/category/<cat>.html      the category hub table (gen_hubs.py)
  web/task/<t>.html            the task hub table (gen_hubs.py)
  web/llms.txt                 the answer-engine feed (gen_hubs.py)
  web/badge/<slug>.svg         the embeddable badge (gen_badges.py)

Four generators, three renderers, one set of facts. They have drifted before — this codebase has
already shipped a hub table whose row anatomy disagreed with the board, a sort reading a column
that had been renamed away, and a nav in six variants. The fix each time was one definition; this
is what proves the definitions stayed one.

FIRST RUN CAUGHT: llms.txt published "[filesystem]" where every other surface said "Filesystem",
because gen_hubs.py had three display sites still calling pretty() after the label landed.

Run: python3 tests/test_consistency.py
"""
import collections, glob, html, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WEB = os.path.join(ROOT, "web")

fail = 0
SAMPLE = int(os.environ.get("CONSISTENCY_SAMPLE", "0"))     # 0 = every capability


def ok(name, cond, detail=""):
    global fail
    if not cond:
        fail = 1
    print(("  ok   " if cond else "  FAIL ") + name + (("  — " + detail) if detail and not cond else ""))


def load(rel):
    p = os.path.join(WEB, rel)
    return json.load(open(p, encoding="utf-8")) if os.path.exists(p) else None


def caps_of(d):
    return d["capabilities"] if isinstance(d, dict) else d


unesc = lambda s: html.unescape(s or "").strip()

# ---- the source of truth -------------------------------------------------------------------------
export = load("data/capabilities.json")
if not export:
    print("  FAIL  web/data/capabilities.json missing — run the export")
    sys.exit(1)
TRUTH = {c["id"]: c for c in caps_of(export)}
print(f"  source of truth: {len(TRUTH)} capabilities in capabilities.json\n")

# ---- 1. the derived JSON payloads ----------------------------------------------------------------
# These are cheap to check exhaustively and are what every client actually reads.
for rel, fields in (("data/index.json", ("label", "tashan_score", "category", "official", "kind",
                                         "expertise_verdict", "npm_pkg")),
                    ("data/lookup.json", ("label", "tashan_score", "category", "official"))):
    d = load(rel)
    if d is None:
        ok(f"{rel} exists", False)
        continue
    rows = d.get("records") if isinstance(d, dict) and "records" in d else caps_of(d)
    rowsById = {r["id"]: r for r in rows}
    missing = [r["id"] for r in rows if r["id"] not in TRUTH]
    if rel.endswith("lookup.json"):
        # lookup.json is ALLOWED to carry rows the board does not, and must: junk() drops
        # registry-deleted entries and the two dependency-confusion canaries off the board, and they
        # survive here so `tashan doctor` can warn somebody already running one. Silence would be the
        # bug. But each survivor needs a REASON — an orphan with no warning attached is just drift.
        # DISCONTINUED is the third reason, added when eligibility began overriding score: a
        # capability whose author, npm or the registry has declared it over loses its score and drops
        # off the board, and it has to stay reachable here or `doctor` answers silence to the person
        # already running it. pkg:docfork is the case that forced the rule — it shipped a working
        # install command while its own description read "DEPRECATED: Use io.github.docfork/docfork
        # instead". These are not orphans; they are the warning.
        unexplained = [i for i in missing
                       if not (rowsById[i].get("registry_status") in ("deleted", "deprecated")
                               or rowsById[i].get("sec_advisory_count")
                               or rowsById[i].get("sec_severity")
                               or rowsById[i].get("npm_deprecated")
                               or rowsById[i].get("self_unmaintained"))]
        ok(f"{rel}: all {len(missing)} board-excluded row(s) are kept deliberately, to warn about",
           not unexplained, f"{len(unexplained)} unexplained orphan(s): {unexplained[:3]}")
    else:
        ok(f"{rel}: every row exists in the export", not missing,
           f"{len(missing)} orphan(s), e.g. {missing[:3]}")
    bad = collections.Counter()
    examples = {}
    for r in rows:
        t = TRUTH.get(r["id"])
        if not t:
            continue
        for f in fields:
            if f in r and r[f] != t.get(f):
                bad[f] += 1
                examples.setdefault(f, f"{r['id']}: {rel}={r[f]!r} export={t.get(f)!r}")
    ok(f"{rel}: {len(rows)} rows agree with the export on {len(fields)} fields",
       not bad, "; ".join(f"{f} differs on {n} row(s) — {examples[f]}" for f, n in bad.most_common(3)))

# ---- 2. the prerendered dossiers -----------------------------------------------------------------
H1 = re.compile(r"<h1>(.*?)</h1>", re.S)
CATLINK = re.compile(r'<b>Category:</b>\s*<a class="link" href="/category/([a-z]+)\.html">')
OFFICIAL = re.compile(r'<span class="official">✓\s*(.*?)\s*·\s*official</span>')
DESC = re.compile(r'<p class="cap-desc">(.*?)</p>', re.S)
SCORE = re.compile(r"tashan score[^0-9]{0,40}([0-9]+(?:\.[0-9]+)?)", re.I)

pages = sorted(glob.glob(os.path.join(WEB, "capability", "*.html")))
if SAMPLE:
    pages = pages[::max(1, len(pages) // SAMPLE)]
slug_to_id = {c.get("slug") or re.sub(r"[^a-z0-9]+", "-", c["id"].lower()).strip("-"): c["id"]
              for c in TRUTH.values()}

mismatch = collections.Counter()
examples = {}
checked = 0
orphan_pages = []
for p in pages:
    slug = os.path.basename(p)[:-5]
    cid = slug_to_id.get(slug)
    if not cid:
        orphan_pages.append(slug)
        continue
    t = TRUTH[cid]
    src = open(p, encoding="utf-8").read()
    checked += 1

    m = H1.search(src)
    want_label = t.get("label") or t.get("name")
    if m:
        got = unesc(re.sub(r"<[^>]+>", "", m.group(1)))
        if got != unesc(want_label):
            mismatch["label"] += 1
            examples.setdefault("label", f"{slug}: page={got!r} export={want_label!r}")

    m = CATLINK.search(src)
    if m and t.get("category") and m.group(1) != t["category"]:
        mismatch["category"] += 1
        examples.setdefault("category", f"{slug}: page={m.group(1)} export={t['category']}")

    m = OFFICIAL.search(src)
    page_official = unesc(m.group(1)) if m else None
    if page_official != (t.get("official") or None):
        mismatch["official"] += 1
        examples.setdefault("official", f"{slug}: page={page_official!r} export={t.get('official')!r}")

    m = DESC.search(src)
    if m and t.get("description"):
        got = unesc(re.sub(r"<[^>]+>", "", m.group(1)))
        if got != unesc(t["description"])[:len(got)]:
            mismatch["description"] += 1
            examples.setdefault("description", f"{slug}: page={got[:50]!r}")

ok(f"every /capability/*.html page corresponds to an exported capability", not orphan_pages,
   f"{len(orphan_pages)} orphan page(s), e.g. {orphan_pages[:3]}")
ok(f"{checked} prerendered dossiers agree with the export (label, category, official, description)",
   not mismatch,
   "; ".join(f"{k} on {n} page(s) — {examples[k]}" for k, n in mismatch.most_common(4)))

# ---- 3. the hub tables ---------------------------------------------------------------------------
# A hub row that names a capability differently from its own dossier is the exact defect that shipped
# once already: a hub table with a different row anatomy from the board.
# Anchor on the LINK, not on any href: the row's <tr data-href=…> carries the same URL, and matching
# that first swallowed the rank cell, so every row read as "1Sequential Thinking".
ROW = re.compile(r'<a class="cap__link" href="/capability/([a-z0-9-]+)\.html">(.*?)</a>', re.S)
hub_bad = collections.Counter()
hub_ex = {}
hub_rows = 0
for hub in sorted(glob.glob(os.path.join(WEB, "category", "*.html")) +
                  glob.glob(os.path.join(WEB, "task", "*.html"))):
    src = open(hub, encoding="utf-8").read()
    cat = os.path.basename(hub)[:-5]
    is_cat = os.path.dirname(hub).endswith("category")
    for slug, inner in ROW.findall(src):
        cid = slug_to_id.get(slug)
        if not cid:
            hub_bad["dead link"] += 1
            hub_ex.setdefault("dead link", f"{os.path.basename(hub)} -> /capability/{slug}.html")
            continue
        t = TRUTH[cid]
        hub_rows += 1
        got = unesc(re.sub(r"<[^>]+>", "", inner))
        want = unesc(t.get("label") or t.get("name"))
        if got and got != want:
            hub_bad["label"] += 1
            hub_ex.setdefault("label", f"{os.path.basename(hub)}: {got!r} vs export {want!r}")
        # a capability must only appear on the hub for the category it is actually in
        if is_cat and t.get("category") and t["category"] != cat:
            hub_bad["wrong hub"] += 1
            hub_ex.setdefault("wrong hub", f"{slug} is '{t['category']}' but listed on /category/{cat}.html")

ok(f"{hub_rows} category/task hub rows name the capability exactly as its dossier does",
   not hub_bad, "; ".join(f"{k} x{n} — {hub_ex[k]}" for k, n in hub_bad.most_common(3)))

# ---- 4. llms.txt — what answer engines quote ------------------------------------------------------
llms = os.path.join(WEB, "llms.txt")
if os.path.exists(llms):
    src = open(llms, encoding="utf-8").read()
    bad, ex = collections.Counter(), {}
    n = 0
    for label, slug, score in re.findall(
            r"- \[([^\]]+)\]\([^)]*?/capability/([a-z0-9-]+)\.html\)\s*—\s*tashan score ([0-9.]+)", src):
        cid = slug_to_id.get(slug)
        if not cid:
            bad["dead link"] += 1
            ex.setdefault("dead link", slug)
            continue
        t = TRUTH[cid]
        n += 1
        if unesc(label) != unesc(t.get("label") or t.get("name")):
            bad["label"] += 1
            ex.setdefault("label", f"llms.txt={label!r} export={(t.get('label') or t.get('name'))!r}")
        if t.get("tashan_score") is not None and float(score) != float(t["tashan_score"]):
            bad["score"] += 1
            ex.setdefault("score", f"{slug}: llms.txt={score} export={t['tashan_score']}")
    ok(f"llms.txt: {n} cited capabilities match the export on name and score",
       not bad, "; ".join(f"{k} x{v} — {ex[k]}" for k, v in bad.most_common(3)))

# ---- 5. badges -----------------------------------------------------------------------------------
# 8,394 badge files against 5,788 pages was the smell that started this check.
# Badges are no longer files — functions/badge/ renders them from web/data/badges.json, because one
# .svg per capability put the site over Cloudflare's 20,000-file deployment limit. Same invariants,
# new storage: globbing the (now empty) directory would have passed vacuously, which is worse than
# failing.
BADGE_MAP = json.load(open(os.path.join(WEB, "data", "badges.json"), encoding="utf-8"))
stale = [s for s in BADGE_MAP if s not in slug_to_id]
ok(f"every one of the {len(BADGE_MAP)} badges belongs to a capability still in the export",
   not stale, f"{len(stale)} badge(s) for capabilities no longer exported, e.g. {stale[:3]}")

# ---- 6. THE NUMBER ITSELF --------------------------------------------------------------------
# Identity being consistent is table stakes; the SCORE is the claim people act on, and it is printed
# on six surfaces by four different code paths. The first version of this file checked it only in the
# JSON payloads and llms.txt — not in the 5,788 rendered dossiers, not in the hub tables, not in the
# badge someone embeds in their README, and not in the JSON-LD an answer engine parses. Those are
# precisely the copies a reader quotes back at you.
DOSSIER_SCORE = re.compile(r"tashan score ([0-9]+(?:\.[0-9]+)?)")
LD_RATING = re.compile(r'"ratingValue":\s*([0-9.]+)')
TITLE = re.compile(r"<title>(.*?)</title>", re.S)

num_bad = collections.Counter()
num_ex = {}
n_scored = 0
for p_ in pages:
    slug = os.path.basename(p_)[:-5]
    cid = slug_to_id.get(slug)
    if not cid:
        continue
    t = TRUTH[cid]
    want = t.get("tashan_score")
    if want is None:
        continue
    src = open(p_, encoding="utf-8").read()
    n_scored += 1

    for rx, key in ((DOSSIER_SCORE, "dossier score"), (LD_RATING, "JSON-LD ratingValue")):
        for got in rx.findall(src):
            if abs(float(got) - float(want)) > 0.05:
                num_bad[key] += 1
                num_ex.setdefault(key, f"{slug}: page={got} export={want}")
                break

    m = TITLE.search(src)
    if m and unesc(t.get("label") or t.get("name")) not in unesc(m.group(1)):
        num_bad["<title> names the capability"] += 1
        num_ex.setdefault("<title> names the capability",
                          f"{slug}: title={unesc(m.group(1))[:44]!r} label={t.get('label')!r}")

ok(f"{n_scored} dossiers print the same tashan score as the export, in body text AND JSON-LD",
   not num_bad, "; ".join(f"{k} wrong on {v} page(s) — {num_ex[k]}" for k, v in num_bad.most_common(3)))

# hub tables print the score in a <span class="sig__val">, rounded
HUBROW = re.compile(
    r'<tr data-href="/capability/([a-z0-9-]+)\.html">.*?<span class="sig__val">([0-9]+)</span>', re.S)
hub_score_bad = collections.Counter()
hsx = {}
n_hub = 0
for hub in sorted(glob.glob(os.path.join(WEB, "category", "*.html")) +
                  glob.glob(os.path.join(WEB, "task", "*.html"))):
    for slug, got in HUBROW.findall(open(hub, encoding="utf-8").read()):
        cid = slug_to_id.get(slug)
        if not cid or TRUTH[cid].get("tashan_score") is None:
            continue
        n_hub += 1
        want = round(float(TRUTH[cid]["tashan_score"]))
        if int(got) != want:
            hub_score_bad[os.path.basename(hub)] += 1
            hsx.setdefault("x", f"{slug} on {os.path.basename(hub)}: hub={got} export={want}")
ok(f"{n_hub} hub rows print the same score as the export",
   not hub_score_bad, hsx.get("x", ""))

# the badge is the copy that ends up in somebody else's README, where we cannot correct it
badge_bad = collections.Counter()
bx = {}
n_badge = 0
for slug, row in sorted(BADGE_MAP.items()):
    cid = slug_to_id.get(slug)
    if not cid or TRUTH[cid].get("tashan_score") is None:
        continue
    n_badge += 1
    # The map holds what the Function will render, so checking it checks the badge. int() not round():
    # gen_badges writes int(trust) and the renderer prints it verbatim.
    want = int(float(TRUTH[cid]["tashan_score"]))
    if int(row[0]) != want:
        badge_bad["score"] += 1
        bx.setdefault("score", f"{slug}: badge={row[0]} export={want}")
ok(f"{n_badge} badges carry the same score as the export",
   not badge_bad, bx.get("score", ""))

# ---- 7. the security audit, on the canonical page ------------------------------------------------
# It lived only in capability.js, which rewrites the dossier client-side — so a person saw the audit
# and a crawler did not, on the one measurement nobody else publishes. Now prerendered. The
# trust-critical assertion is the negative one: a capability we did NOT scan must never render a
# sentence that could be read as "we scanned it and it was clean".
sec_bad = collections.Counter()
sec_ex = {}
n_scanned = n_unscanned = 0
for p_ in pages:
    cid = slug_to_id.get(os.path.basename(p_)[:-5])
    if not cid:
        continue
    t = TRUTH[cid]
    src = open(p_, encoding="utf-8").read()
    slug = os.path.basename(p_)[:-5]

    if "Security audit" not in src:
        sec_bad["no security section at all"] += 1
        sec_ex.setdefault("no security section at all", slug)
        continue

    if not t.get("sec_scanned_at"):
        n_unscanned += 1
        if "Not scanned yet" not in src:
            sec_bad["unscanned page does not say so"] += 1
            sec_ex.setdefault("unscanned page does not say so", slug)
        for claim in ("No known advisories", "checked against OSV", "No permission surface detected"):
            if claim in src:
                sec_bad["unscanned page implies a clean scan"] += 1
                sec_ex.setdefault("unscanned page implies a clean scan", f"{slug}: {claim!r}")
                break
        continue

    n_scanned += 1
    n_adv = t.get("sec_advisory_count") or 0
    if n_adv and f"{n_adv} known advisor" not in src:
        sec_bad["advisory count"] += 1
        sec_ex.setdefault("advisory count", f"{slug}: export says {n_adv}")
    if not n_adv and "No known advisories" not in src:
        sec_bad["clear result not stated"] += 1
        sec_ex.setdefault("clear result not stated", slug)
    if bool(t.get("sec_install_script")) != ("Runs a script at install time" in src):
        sec_bad["install script"] += 1
        sec_ex.setdefault("install script", f"{slug}: export={bool(t.get('sec_install_script'))}")
    if bool(t.get("sec_provenance")) != ("Signed build provenance" in src):
        sec_bad["provenance"] += 1
        sec_ex.setdefault("provenance", f"{slug}: export={bool(t.get('sec_provenance'))}")

ok(f"{n_scanned} scanned + {n_unscanned} unscanned dossiers state their security result truthfully",
   not sec_bad, "; ".join(f"{k} x{v} — {sec_ex[k]}" for k, v in sec_bad.most_common(3)))

# ---- 8. the security audit must be FREE, in full, in every public file ---------------------------
# This block used to assert the opposite: that sec_advisories and the literal install command were
# ABSENT from the public files, because they were the paid half. They are now free. Naming a
# vulnerability and charging for its identity and its fix is the one thing an independent rater
# cannot do, so the gate was deleted rather than tightened — see build.py::redact_paid.
#
# The assertion is inverted, not dropped, because the failure mode is real in both directions: the
# detail was once silently truncated to "protect revenue" and the free promise broke without a
# sound. What must never regress is the WHOLE audit being readable by anyone with curl.
FREE_FLOOR = ("sec_permissions", "sec_install_script")
for rel in ("data/capabilities.json",):
    d = load(rel)
    if d is None:
        continue
    rows = d.get("records") if isinstance(d, dict) and "records" in d else caps_of(d)
    booleaned = sum(1 for r in rows if r.get("sec_install_script") is True)
    real = sum(1 for r in rows if isinstance(r.get("sec_install_script"), str))
    ok(f"{rel} publishes the real install command, not a boolean — {real} capabilities",
       real > 0 and booleaned == 0,
       f"{booleaned} row(s) still carry sec_install_script as a bare True; the command is free now")

# The permission surface must stay whole in the public export — the free column sells it.
_exp = caps_of(load("data/capabilities.json"))
_withperms = [c for c in _exp if c.get("sec_permissions")]
_multi = sum(1 for c in _withperms
             if len((json.loads(c["sec_permissions"]) if isinstance(c["sec_permissions"], str)
                     else c["sec_permissions"])) > 1)
ok(f"the full permission surface stays free — {_multi} capabilities publish more than one",
   _multi > 0, "every permission list was truncated to one entry; the free tier promises "
               "'what it can reach on your machine' and the headline read needs it to warn")

# ...and the free claim must still be intact, or the fix above quietly became a downgrade
idx_rows = caps_of(load("data/index.json"))
free_signal = sum(1 for r in idx_rows if r.get("sec_advisory_count") is not None
                  or r.get("sec_install_script") or r.get("sec_permissions"))
ok(f"the free tier still names a finding on {free_signal} board rows", free_signal > 0,
   "redaction removed the free signal too")

# ---- 9. every remaining DISPLAYED value ----------------------------------------------------------
# A field nobody renders cannot be inconsistent, so the set worth checking is exactly what a reader
# sees. Identity, score and the security result are covered above; this closes the rest — the
# vitality chip, the expertise verdict, the evidence cell and the freshness column — plus the inline
# JSON payload each dossier embeds, which is a FOURTH public copy of the record and had to be
# redacted along with the JSON files.
# The real tag is <script type="application/json" id="cap-data">. An earlier pattern here matched
# nothing and the check reported "0 payloads ... ok" — a green test that verified nothing, which is
# the failure mode this whole file exists to catch. The count is asserted non-zero below.
INLINE = re.compile(r'<script type="application/json" id="cap-data">(.*?)</script>', re.S)
# NOT a list of fields to keep in step with the UI — that list rots the moment someone renders one
# more column. capability.js renders FROM this payload, so asserting the payload equals the export on
# every key it carries covers everything displayed, now and after the next feature, with one rule.
SKIP = {"at",          # the render timestamp, which is about the page and not the capability
        "co_used"}     # deliberately FILTERED, not copied — asserted separately just below
inline_bad = collections.Counter()
inline_ex = {}
n_inline = 0
paid_inline = collections.Counter()
for p_ in pages:
    cid = slug_to_id.get(os.path.basename(p_)[:-5])
    if not cid:
        continue
    m = INLINE.search(open(p_, encoding="utf-8").read())
    if not m:
        continue
    try:
        blob = json.loads(m.group(1))
    except Exception:
        inline_bad["unparseable inline payload"] += 1
        continue
    c = blob.get("c") or blob
    t = TRUTH[cid]
    n_inline += 1
    for f in set(c) - SKIP:
        if c[f] != t.get(f):
            inline_bad[f] += 1
            inline_ex.setdefault(f, f"{os.path.basename(p_)}: inline={c[f]!r} export={t.get(f)!r}")
    if c.get("sec_advisories") or isinstance(c.get("sec_install_script"), str):
        paid_inline["paid detail"] += 1

    # co_used is the one field the dossier deliberately narrows: prerender drops co-use links to
    # capabilities it did not write a page for, because linking to a missing page 404s. So it is not
    # equality — it is "a subset of the export's, and every survivor has a page". Asserting equality
    # here would have forced a real correctness feature to be reverted to satisfy a test.
    want_co = {x["id"] for x in (t.get("co_used") or [])}
    for x in (c.get("co_used") or []):
        if x["id"] not in want_co:
            inline_bad["co_used invented a link"] += 1
            inline_ex.setdefault("co_used invented a link", f"{os.path.basename(p_)}: {x['id']}")
        elif x["id"] not in TRUTH:
            inline_bad["co_used links a capability with no page"] += 1
            inline_ex.setdefault("co_used links a capability with no page",
                                 f"{os.path.basename(p_)}: {x['id']}")

ok(f"the inline payload was actually found and parsed on all {len(pages)} dossiers",
   n_inline == len(pages), f"parsed {n_inline} of {len(pages)} — the selector is wrong, not the data")
ok(f"{n_inline} inline dossier payloads agree with the export on EVERY field they carry",
   not inline_bad, "; ".join(f"{k} on {n} page(s) — {inline_ex.get(k,'')}" for k, n in inline_bad.most_common(3)))
# Inverted with the block above: the island must CARRY the audit detail, because capability.js
# renders the dossier from it and a reader with JS must not see less than the static page shows.
ok("the inline dossier payload carries the audit detail, not a redacted copy",
   n_inline > 0 and sum(paid_inline.values()) > 0,
   "no dossier island embeds the install command — the client render will show less than the server")

# ---- 10. eligibility beats the score ------------------------------------------------------------
# pkg:docfork carried tashan score 55, ranked 19th on its category hub, and printed a copy-pasteable
# `npx -y docfork` install snippet — while the npm description we ourselves published on that page
# read "Up-to-date docs for AI. DEPRECATED: Use io.github.docfork/docfork instead."
#
# Every input to the score was honest: it was published recently, by a live maintainer, with real
# downloads. That is exactly the problem — upkeep signal keeps looking healthy for months after the
# author has moved on, so a computed number cannot notice a retirement. self_unmaintained is read off
# the capability's OWN text, which is the one source that outranks every derived signal. When it is
# set the answer is not "score it lower", it is "do not rank it at all": a 55 next to a working
# install command is an instruction to install something its publisher has retired.
self_dead = [c for c in TRUTH.values() if c.get("self_unmaintained")]
scored_dead = [f"{c['id']} scores {c['tashan_score']} but says {str(c['self_unmaintained'])[:60]!r}"
               for c in self_dead if c.get("tashan_score") is not None]
ok(f"none of the {len(self_dead)} self-declared-discontinued capabilities carries a tashan score",
   not scored_dead, "; ".join(scored_dead[:3]))

# ---- 11. …and a discontinued capability stays REACHABLE ------------------------------------------
# The other half of the same fix, and the half that is easy to get wrong: dropping docfork off the
# board is right, dropping it out of lookup.json is not. lookup.json is what `tashan doctor` reads,
# and the person who most needs to hear "this is deprecated, here is the replacement" is the person
# who already has `npx -y docfork` in their config today. If the row vanishes, doctor answers them
# with silence, which reads as "nothing wrong with it" — the same failure §1 guards for the
# registry-deleted rows and the two dependency-confusion canaries.
#
# lookup.json's `keys` maps a lookup string to an INDEX into `records`, not to an id, so reachability
# has to be resolved through records[i]["id"] — comparing keys to ids directly finds nothing and the
# check would pass on an empty set.
_look = load("data/lookup.json") or {}
_lrecs = _look.get("records") or []
_reachable = {_lrecs[i]["id"] for i in _look.get("keys", {}).values() if 0 <= i < len(_lrecs)}
_dead_ids = ({r["id"] for r in _lrecs if r.get("self_unmaintained")} |
             {c["id"] for c in self_dead})
_unreachable = sorted(_dead_ids - _reachable)
ok(f"all {len(_dead_ids)} self-declared-discontinued capabilities are resolvable in lookup.json",
   not _unreachable,
   f"{len(_unreachable)} can never be found by `tashan doctor`, e.g. {_unreachable[:3]}")
# Named because it is the incident: docfork must resolve from the BARE name a config actually
# carries ("docfork" in `npx -y docfork`), not only from our internal id.
_docfork = [k for k, i in _look.get("keys", {}).items()
            if 0 <= i < len(_lrecs) and _lrecs[i]["id"] == "pkg:docfork"]
ok("pkg:docfork — dropped off the board as deprecated — is still resolvable by its bare npm name",
   "docfork" in _docfork and "pkg:docfork" in _docfork,
   f"lookup keys for pkg:docfork: {_docfork or 'none — doctor answers silence to everyone running it'}")

# ---- 12. no licence language where the thing is free ---------------------------------------------
# The security audit is free in full — advisory ids, fixed versions, the literal install command. The
# copy did not all move at once: 218 generated compare pages went on printing "the detail a licence
# buys is on each dossier" long after the licence stopped buying anything, so a reader was told to pay
# for a fact sitting one click away, free. Wrong-in-our-favour copy is worse than a stale number; it
# reads as a bait-and-switch by an outfit whose entire pitch is that it does not sell the answer.
#
# "behind a licence" is on the list because it was the phrasing, but the FIX uses the same words in
# the negative — every dossier now closes with "Nothing in this audit is behind a licence." That one
# sentence is subtracted before the sweep; any other appearance of the phrase still fails.
PAYWALL = ("licence buys", "unlock detail", "behind a licence")
FREE_PROMISE = "Nothing in this audit is behind a licence"
sweep = []
for _d in ("compare", "category", "task", "role"):
    sweep += sorted(glob.glob(os.path.join(WEB, _d, "*.html")))
# 5,900 dossiers all render from one template, so a stride sample proves the template; the small
# hand-built page sets above are swept whole.
sweep += pages[::max(1, len(pages) // 200)]
sold = collections.Counter()
sold_ex = {}
for p_ in sweep:
    src = open(p_, encoding="utf-8").read().replace(FREE_PROMISE, "")
    for phrase in PAYWALL:
        if phrase in src:
            sold[phrase] += 1
            sold_ex.setdefault(phrase, os.path.relpath(p_, WEB))
ok(f"{len(sweep)} sampled generated pages sell nothing that is already free",
   not sold, "; ".join(f"{k!r} on {n} page(s), e.g. {sold_ex[k]}" for k, n in sold.most_common(3)))

# ---- 13. every job mapping carries its evidence --------------------------------------------------
# The task mapping is the half of the product nobody else has: "which capability actually does this
# job". That makes it the half with no external check on it — a registry entry is wrong publicly, a
# job mapping is only wrong to the person who trusted it. An entry with a fit level but no `e` string
# is an unsupported claim wearing the same chrome as a supported one, and it renders identically on
# /task/*.html, so nothing downstream can tell them apart. Fit must also be one of the three we
# publish and rank on; a fourth value sorts arbitrarily and shows up as a blank column.
FITS = {"primary", "supporting", "incidental"}
task_bad = collections.Counter()
task_ex = {}
n_task = 0
for c in TRUTH.values():
    t = c.get("tasks")
    if not t:
        continue
    if isinstance(t, str):
        try:
            t = json.loads(t)
        except Exception:
            task_bad["unparseable tasks blob"] += 1
            task_ex.setdefault("unparseable tasks blob", c["id"])
            continue
    for e in t:
        n_task += 1
        if not isinstance(e, dict):
            task_bad["entry is not an object"] += 1
            task_ex.setdefault("entry is not an object", f"{c['id']}: {e!r}")
            continue
        if e.get("f") not in FITS:
            task_bad["fit level not in {primary,supporting,incidental}"] += 1
            task_ex.setdefault("fit level not in {primary,supporting,incidental}",
                               f"{c['id']} -> {e.get('t')!r}: f={e.get('f')!r}")
        if not str(e.get("e") or "").strip():
            task_bad["no evidence"] += 1
            task_ex.setdefault("no evidence", f"{c['id']} -> {e.get('t')!r} claims {e.get('f')!r} "
                                              "fit with nothing behind it")
ok(f"all {n_task} task mappings state a fit level AND the evidence for it",
   not task_bad, "; ".join(f"{k} x{n} — {task_ex[k]}" for k, n in task_bad.most_common(3)))

# ---- 14. coverage is never overstated -------------------------------------------------------------
# index.json's header is the site's own claim about how much of the corpus it has actually measured,
# and it is quoted straight onto the homepage. It once printed a percentage over 100 because the
# denominator was the wrong key — more capabilities "risk scanned" than existed to scan. A ratio
# above 1.0 is not a rounding artefact, it is proof the two numbers count different populations, and
# it lands on the one page that has to be credible on first read.
_idx = load("data/index.json") or {}
_denom = _idx.get("coverage_of")
over = [f"{k}={_idx.get(k)} > coverage_of={_denom}"
        for k in ("risk_scanned", "expertise_graded", "job_mapped")
        if isinstance(_idx.get(k), int) and isinstance(_denom, int) and _idx[k] > _denom]
ok(f"index.json: risk_scanned/expertise_graded/job_mapped all fit inside coverage_of={_denom}",
   isinstance(_denom, int) and _denom > 0 and not over,
   "; ".join(over) or f"coverage_of is {_denom!r} — the denominator every coverage percentage divides by")

print("\nCONSISTENCY FAILED" if fail else "\nok — one capability, one set of facts, every surface")
sys.exit(fail)
